/* =============================================
   MUNDO ROMIX — Banco de mensajes aleatorios
   365+ mensajes únicos para todo el año
   ============================================= */

const MENSAJES_ALEATORIOS = [
  // --- AMOR PROFUNDO ---
  "Cada día a tu lado es un regalo que no merezco pero agradezco infinitamente. 💝",
  "Si pudiera elegir a alguien para recorrer el mundo, siempre te elegiría a ti. 🌎",
  "Eres mi lugar favorito en el universo. 🌌",
  "Contigo aprendí que el amor no se busca, simplemente llega y lo cambia todo. ✨",
  "Me haces querer ser la mejor versión de mí mismo cada día. 🦋",
  "Eres la razón por la que creo en cosas bonitas. 🌸",
  "Mi parte favorita del día es cuando te veo sonreír. 😊",
  "Si el amor fuera tiempo, contigo la eternidad se quedaría corta. ⏳",
  "Gracias por elegirme todos los días. Te amo infinitamente. 💫",
  "Eres mi calma en medio del caos y mi aventura en los días aburridos. 🎢",
  "No sé qué hice para merecerte, pero lo haría un millón de veces más. 💎",
  "Mi corazón es tuyo, desde el primer día y para siempre. 🔐",
  "Si el amor fuera un color, sería el rosa de tus mejillas. 🌷",
  "Eres la canción favorita que nunca me canso de escuchar. 🎵",
  "Tú eres mi hogar, no importa dónde estemos. 🏡",
  "Te amo más de lo que las palabras pueden expresar. 📝",
  "Eres el sueño del que no quiero despertar jamás. 🌙",
  "Cada latido de mi corazón lleva tu nombre. 💓",
  "Eres la estrella más brillante de mi cielo. ⭐",
  "Me enamoré de ti y no pienso buscar la cura. 💘",
  "Contigo descubrí lo que significa amar de verdad. 🔥",
  "Eres lo mejor que me ha pasado en la vida. 🏆",
  "Mi alma encontró su hogar cuando te conoció a ti. 🏠",
  "Te elegiría en cualquier vida, en cualquier universo. 🪐",
  "Amarte es la decisión más fácil que tomo cada día. 💕",
  "Eres mi principio y mi final favorito. 📖",
  "Cada momento contigo es un tesoro que guardo en el alma. 💰",
  "Tu sonrisa es la medicina que cura todos mis males. 😄",
  "Eres la poesía que mi corazón siempre quiso escribir. ✍️",
  "Me haces sentir que todo es posible cuando estamos juntos. 🚀",
  // --- TIERNOS ---
  "Hoy me desperté pensando en lo afortunado que soy por tenerte. 🍀",
  "Si me preguntaran qué es la felicidad, diría tu nombre. 😍",
  "Eres el abrazo que necesito sin pedirlo. 🤗",
  "Cada vez que te veo, me enamoro un poquito más. 🥰",
  "Eres mi sol en los días nublados. ☀️",
  "Me encanta cómo haces que lo ordinario se vuelva extraordinario. ✨",
  "No necesito el paraíso, ya te tengo a ti. 🌺",
  "Si pudiera detener el tiempo, lo haría en cada momento contigo. ⏰",
  "Eres la persona con la que quiero envejecer. 👴👵",
  "Me robaste el corazón y no quiero que lo devuelvas. 💖",
  "Eres mi primera sonrisa del día y mi último pensamiento. 😴",
  "Contigo aprendí que los cuentos de hadas sí existen. 🏰",
  "Mi mundo gira mejor cuando estás en él. 🌍",
  "Eres esa persona que hace que todo valga la pena. 💪",
  "Si fueras una flor, serías la más hermosa del jardín. 🌹",
  "Tu voz es mi melodía favorita. 🎶",
  "Eres el chocolate caliente en mis días de frío. ☕",
  "No sé qué hubiera sido de mí sin encontrarte. 🙏",
  "Cada aventura contigo es mi favorita. 🗺️",
  "Me haces creer que el amor verdadero existe. 💞",
  "Eres el regalo más bonito que la vida me ha dado. 🎁",
  "Me encanta cada versión de ti: la feliz, la pensativa, todas. 🎭",
  "Cuando estoy contigo, el tiempo se detiene y vuela al mismo tiempo. ⌛",
  "Tu risa es la banda sonora de mi vida. 😂",
  "Eres la respuesta a todas las preguntas de mi corazón. ❓💗",
  "Contigo los problemas pesan menos y las alegrías pesan más. ⚖️",
  "Eres mi persona, mi equipo, mi todo. 👫",
  "No cambiaría ni un segundo de lo que hemos vivido juntos. 📸",
  "Eres ese tipo de amor que solo se encuentra una vez. 💎",
  "Me haces sentir mariposas cada vez que me miras. 🦋",
  // --- GRACIOSOS / DULCES ---
  "Contigo el mundo tiene mejor WiFi. 📶😂",
  "A tu lado, hasta el lunes se siente como viernes. 🎉",
  "Te quiero más que al chocolate, y eso ya es decir mucho. 🍫",
  "Eres mi persona favorita, hoy, mañana y siempre. 💗",
  "Si te extrañar quemara calorías, ya sería modelo de fitness. 😜",
  "Eres la notificación que siempre quiero recibir. 📱",
  "Debería existir un emoji solo para lo que siento por ti. 🤯",
  "Eres mi serie favorita en modo maratón infinito. 📺",
  "Si fueras un meme, serías el más viral de todos. 😆",
  "Te quiero más que a la pizza, y eso es amor del bueno. 🍕",
  "Mi corazón hace WiFi automático contigo: se conecta solo. 📡",
  "Eres el snack que siempre quiero a mi lado. 🍿",
  "Si el amor fuera un deporte, tú serías mi MVP. 🏅",
  "Contigo hasta hacer nada es el mejor plan. 🛋️",
  "Me gustas más que dormir, y yo AMO dormir. 😴💤",
  "Eres como el café: me despiertas y me aceleras el corazón. ☕",
  "Si fueras un día de la semana, serías viernes por siempre. 🥳",
  "Eres la persona con la que quiero compartir mis papas fritas. 🍟",
  "Mi corazón tiene un screensaver y eres tú. 💻",
  "Eres el cheat code de mi felicidad. 🎮",
  "Te quiero más que a mi playlist favorita. 🎧",
  "Si fueras un postre, serías el más dulce del menú. 🍰",
  // --- ROMÁNTICOS ---
  "Tus ojos son el mapa que me lleva a casa. 👀",
  "Besar tus labios es mi actividad favorita en el mundo. 💋",
  "Eres la magia que hace que mi vida tenga sentido. 🪄",
  "Cada noche sueño contigo, y cada mañana me doy cuenta de que la realidad es mejor. 🌅",
  "Eres el tipo de amor que inspira canciones y poemas. 🎼",
  "Me pierdo en tus ojos y no quiero que nadie me encuentre. 🔮",
  "Tu piel es mi lugar seguro en este mundo loco. 🤍",
  "Si tuviera que escribir nuestra historia, necesitaría infinitas páginas. 📚",
  "Eres la brisa suave que calma mis tormentas. 🌬️",
  "Cada beso tuyo es un poema sin palabras. 💏",
  "Eres la luna que ilumina mis noches más oscuras. 🌕",
  "Me tienes loco, y es la mejor locura que he vivido. 🤪",
  "Tu amor es el oxígeno que mis pulmones necesitan. 🌬️",
  "Eres la pintura más hermosa en el lienzo de mi vida. 🎨",
  "Cada caricia tuya me recuerda por qué estoy vivo. 🖐️",
  "Eres el verso más bonito de mi canción favorita. 🎤",
  "Tu amor me hace sentir invencible. 💪✨",
  "Eres el atardecer que pinto en mi mente cada noche. 🌇",
  "Abrazar tu cuerpo es como encontrar la paz en un abrazo. 🫂",
  "Eres mi locura favorita, mi caos perfecto. 🌀",
  // --- AGRADECIMIENTO ---
  "Gracias por hacer de mi vida algo extraordinario. 🙌",
  "Gracias por cada risa, cada abrazo, cada momento. 😁",
  "Soy mejor persona porque tú existes en mi vida. 🌟",
  "Gracias por aguantar mis locuras y amarme igual. 🤡💖",
  "Contigo aprendí que la gratitud se siente con el corazón. 🙏",
  "Gracias por ser mi paz cuando el mundo es ruido. 🔇",
  "No me alcanzan las gracias por todo lo que me das. 🎀",
  "Valoro cada segundo que pasamos juntos. ⏱️",
  "Gracias por creer en mí cuando ni yo mismo lo hacía. 💪",
  "Eres mi mayor bendición disfrazada de persona. 😇",
  "Gracias por hacerme reír cuando más lo necesito. 😂",
  "Eres la prueba de que las cosas buenas llegan. 🎯",
  "Gracias por ser mi compañera de vida, de sueños y de locuras. 👫",
  "Me siento millonario solo por tenerte a mi lado. 💰",
  "Gracias por enseñarme lo que es el amor de verdad. 📖",
  // --- FUTURO JUNTOS ---
  "Quiero envejecer a tu lado viendo atardeceres. 🌅",
  "Nuestro futuro juntos va a ser épico, lo presiento. 🔮",
  "Quiero construir un mundo contigo, ladrillo a ladrillo. 🧱",
  "Sueño con el día en que despertemos juntos cada mañana. 🌄",
  "Contigo quiero vivir mil aventuras más. 🏔️",
  "El futuro me emociona porque sé que estarás en él. 🎆",
  "Planeo amarte hasta que las estrellas se apaguen. ✨",
  "Quiero que seas la última persona que vea cada noche. 🌙",
  "Nuestros mejores capítulos aún están por escribirse. ✏️",
  "Un día miraremos atrás y diremos: valió cada segundo. 📷",
  "Quiero darte el mundo entero, y voy a trabajar para eso. 🌏",
  "Cada plan que hago tiene tu nombre escrito en él. 📋",
  "Sueño con una casita donde vivamos nuestro cuento. 🏡💕",
  "El mejor viaje de mi vida es el que hago contigo. ✈️",
  "Quiero despertar cada mañana y elegirte de nuevo. 🌞",
  // --- ADMIRACIÓN ---
  "Me impresionas cada día con tu fuerza y tu luz. 💡",
  "Eres la mujer más increíble que he conocido. 👑",
  "Tu inteligencia me enamora tanto como tu sonrisa. 🧠💖",
  "Admiro cómo luchas por lo que quieres, eres inspiradora. 🔥",
  "Eres fuerte, hermosa e inteligente. El paquete completo. 🎀",
  "Me encanta tu forma de ver el mundo, es única. 🌈",
  "Eres una guerrera y una princesa al mismo tiempo. ⚔️👸",
  "Tu bondad hace del mundo un lugar mejor. 🕊️",
  "Cada cosa que haces la haces con tanta pasión que me enamora. 🔥",
  "Eres arte caminando y ni siquiera lo sabes. 🖼️",
  "Tu determinación es una de las cosas que más amo de ti. 💯",
  "Eres luz propia, nunca dejes que nadie te apague. 🔆",
  "Me inspiras a soñar más grande cada día. 🌠",
  "Tu corazón es el más hermoso que he conocido. ❤️‍🔥",
  "Eres la definición de mujer extraordinaria. 🌟",
  // --- COTIDIANOS ---
  "Hoy quiero recordarte que eres amada más de lo que imaginas. 💌",
  "Espero que tu día sea tan hermoso como tú. 🌻",
  "Solo quería decirte: te amo, con todo y tus manías. 😄",
  "Hoy es un buen día porque existes en mi vida. ☀️",
  "Ojalá pudiera abrazarte ahora mismo. 🤗",
  "Pienso en ti más de lo que crees. 💭",
  "Eres lo primero que se me viene a la mente al despertar. 🌅",
  "Extraño tu risa, tu olor, tu todo. 🥺",
  "Hoy te mando un abrazo virtual cargado de amor. 📩",
  "Que sepas que hoy y siempre, estoy orgulloso de ti. 🏅",
  "Me haces falta cuando no estás, pero te llevo siempre conmigo. 💗",
  "Hoy el cielo está bonito, pero no tanto como tú. 🌤️",
  "Solo pasé por aquí para decirte que te quiero mucho. 💕",
  "Eres mi pensamiento favorito del día. 🧠💖",
  "Que este mensaje te arranque una sonrisa: TE AMO. 😁",
  // --- POÉTICOS ---
  "Eres la tinta con la que escribo mi mejor historia. ✒️",
  "En el libro de mi vida, tú eres el capítulo más bonito. 📕",
  "Eres el silencio perfecto después de una tormenta. 🌧️➡️☀️",
  "Como la luna al mar, tú mueves todo en mí. 🌊",
  "Eres el suspiro que se escapa cuando pienso en lo mucho que te amo. 😮‍💨",
  "Si fueras una estación, serías primavera: llena de vida y color. 🌼",
  "Eres el eco de un sueño que no quiero que termine nunca. 🔔",
  "Tu amor es como el agua: esencial, puro y vital. 💧",
  "Eres la nota más alta en la sinfonía de mi vida. 🎻",
  "Como el sol necesita el cielo, yo te necesito a ti. ☀️🌤️",
  "Eres el perfume que impregna todos mis recuerdos bonitos. 🌺",
  "Tu amor es un río que me lleva a lugares hermosos. 🏞️",
  "Eres la chispa que enciende cada uno de mis días. 🔥",
  "Como la lluvia a la tierra, tu amor me hace florecer. 🌱",
  "Eres el horizonte al que siempre quiero llegar. 🌅",
  // --- MOTIVACIONALES ---
  "Juntos podemos con todo lo que la vida nos ponga enfrente. 💪",
  "Eres mi motivación para levantarme cada mañana. ⏰",
  "No hay obstáculo que no podamos superar de la mano. 🤝",
  "Confío en nosotros más que en cualquier otra cosa. 🛡️",
  "Nuestro amor es prueba de que las cosas hermosas existen. 🌈",
  "Cada reto que enfrentamos nos hace más fuertes como equipo. 💯",
  "Tú me enseñaste que el amor no es debilidad, es poder. ⚡",
  "Somos imparables cuando estamos juntos. 🚀",
  "Contigo no le tengo miedo a nada. 🦁",
  "Eres mi razón para nunca rendirme. 🏁",
  // --- EXTRAS ---
  "Si las estrellas fueran deseos, pediría tenerte siempre. ⭐",
  "Eres el plot twist más hermoso de mi historia. 📖",
  "Me tienes más enganchado que mi serie favorita. 📺",
  "Si el amor midiera en gigas, el nuestro sería ilimitado. ♾️",
  "Eres la razón por la que sonrío sin motivo aparente. 😊",
  "Me haces tan feliz que a veces no me lo creo. 🤯",
  "Cada día descubro algo nuevo que amo de ti. 🔍",
  "Eres mi favorita entre siete mil millones de personas. 🌍",
  "Tu amor es el mejor regalo que he recibido. 🎁",
  "Eres la prueba de que Dios me quiere mucho. 🙏",
  "Contigo los días grises se vuelven de colores. 🎨",
  "Eres lo que siempre pedí y nunca imaginé encontrar. ✨",
  "Si me dieran a elegir de nuevo, te elegiría mil veces más. 🔄",
  "Tu amor es mi superpoder secreto. 🦸",
  "Eres la mejor compañera de equipo que podría tener. 🤝",
  "Me haces sentir que vuelo cuando estoy contigo. 🕊️",
  "Eres el tipo de felicidad que no se puede comprar. 💸",
  "Tu abrazo es el lugar donde todos mis miedos desaparecen. 🤗",
  "Eres mi persona favorita para no hacer nada juntos. 😌",
  "Me enamoré de tu alma antes que de tu cara, y eso dice mucho. 🌟",
  "Eres mi definición de perfecto imperfecto. 💫",
  "Cada día me convenzo más de que fuimos hechos el uno para el otro. 🧩",
  "Eres el capítulo que jamás quiero terminar de leer. 📖",
  "Me haces sentir cosas que creí que solo existían en películas. 🎬",
  "Tu voz diciendo mi nombre es mi sonido favorito. 🎙️",
  "Eres mi amuleto de buena suerte. 🍀",
  "Si pudiera embotellar este amor, sería millonario. 🧴💰",
  "Eres lo que los poetas intentan describir pero no pueden. ✍️",
  "Mi lista de cosas favoritas empieza y termina contigo. 📝",
  "Eres el motivo por el que creo en los finales felices. 🎬💕",
  "No necesito Google, tú eres la respuesta a todo. 🔍",
  "Eres más adictiva que el café de la mañana. ☕",
  "Contigo aprendí que el amor no es perfecto, es real. 💎",
  "Eres la constante en la ecuación de mi felicidad. ➕",
  "Si el amor fuera un examen, sacaría 10 amándote. 📝",
  "Eres el tipo de persona que aparece una vez en la vida. 🌠",
  "Mi corazón dice tu nombre con cada latido. 💓",
  "Eres la mejor decisión que he tomado sin pensarlo. ✅",
  "Tu risa es contagiosa y tu amor es eterno. 😄♾️",
  "Me haces querer escribirte canciones aunque no sepa cantar. 🎤",
  "Eres la vitamina que me da energía para todo. 💊",
  "Contigo aprendí que el hogar no es un lugar, es una persona. 🏠❤️",
  "Eres mi paz, mi guerra, mi todo. 🕊️⚔️💫",
  "Me faltan idiomas para decirte cuánto te amo. 🌐",
  "Eres el WiFi gratis de mi corazón: siempre conectada. 📶",
  "Si fueras una hora del día, serías las 11:11 — mi deseo eterno. 🕚",
  "Eres tan especial que deberían hacer un día festivo en tu honor. 🎊",
  "Mi GPS sentimental siempre me lleva hacia ti. 📍",
  "Eres el arcoíris después de cada tormenta en mi vida. 🌈",
  "Me gustas tanto que me duelen las mejillas de sonreír. 😁",
  "Si regalaran besos, te daría acciones ilimitadas. 💋♾️",
  "Eres la cereza en el pastel de mi existencia. 🍒",
  "Pensar en ti es mi hobby favorito. 💭",
  "Si el amor fuera un océano, el nuestro no tendría orillas. 🌊",
  "Eres mi estrella polar: siempre me guías a casa. ⭐🧭",
  "No existe filtro de Instagram que te haga más hermosa de lo que ya eres. 📸",
  "Eres la playlist perfecta para cualquier momento de mi vida. 🎶",
  "Tu sonrisa debería ser patrimonio de la humanidad. 😊🌍",
  "Me siento como si hubiera ganado la lotería del amor contigo. 🎰",
  "Eres la excepción a todas mis reglas. 📏💕",
  "Tu amor es la mejor inversión que he hecho en mi vida. 📈",
  "Eres la taza de chocolate caliente en mis noches frías. 🍫☕",
  "Cada mensaje tuyo acelera mi corazón como una montaña rusa. 🎢",
  "Si te midieran en estrellas, serías una galaxia entera. 🌌",
  "Eres mi persona favorita para mandarle memes a las 3am. 😂📱",
  "Me enamoré de ti como quien no quiere la cosa, y ahora no puedo parar. 🌀💘",
  "Eres el pixel más brillante en la pantalla de mi vida. ✨🖥️"
];
